config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: :registration
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'home/index'
  root to: 'home#index'

  resources :users
  resources :user_loans
  resources :products
  resources :product_variants
  resources :payment_schedules
  resources :invoices
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id            :integer          not null, primary key
#  address       :string
#  date_of_birth :date
#  gender        :string
#  images        :
#  name          :string
#  phone_number  :string
#  profile_photo :attachments
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class User < ApplicationRecord
  paginates_per 20
  has_one_attached :profile_photo, dependent: :destroy
  has_many_attached :images, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.order(:id).page params[:page]
  end

  # rubocop:disable Metrics/MethodLength
  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  # rubocop:disable Metrics/MethodLength
  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy

    redirect_to users_path, status: :ok
  end

  private

  def user_params
    params.require(:user).permit(:name, :address, :date_of_birth, :gender,
                                 :phone_number, :profile_photo, images: [])
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_form.html.erb
<p data-controller="user"></p>
<%= form_with model: user, class: 'row' do |form| %>
  <div class="col-10 mb-4">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
    <% user.errors.full_messages_for(:name).each do |message| %>
      <div class="invalid-feedback"><%= message %></div>
    <% end %>
  </div>

  <div class="col-10 mb-4">
    <%= form.label :date_of_birth, class: "form-label" %>
    <%= form.text_field :date_of_birth, type: :date, class: "form-control" %>
    <% user.errors.full_messages_for(:date_of_birth).each do |message| %>
      <div class="invalid-feedback"><%= message %></div>
    <% end %>
  </div>

  <div class="col-10 mb-4">
    <%= form.label :phone_number, class: "form-label" %>
    <%= form.text_field :phone_number, type: :number_to_phone, class: "form-control" %>
    <% user.errors.full_messages_for(:phone_number).each do |message| %>
      <div class="invalid-feedback"><%= message %></div>
    <% end %>
  </div>

  <div class="col-10 mb-4">
    <%= form.label :address, class: "form-label" %>
    <%= form.text_area :address, class: "form-control" %>
    <% user.errors.full_messages_for(:address).each do |message| %>
      <div class="invalid-feedback"><%= message %></div>
    <% end %>
  </div>

  <div class="col-10 mb-4" data-controller="upload">
    <%= form.label :profile_photo, class: "form-label" %>
    <%= form.file_field :profile_photo, direct_upload: true, data: { upload_target: 'input', action: "change->upload#uploadFile" } %>
    <div>
      <% if user.profile_photo.representable? %>
        Profile Photo: <%= image_tag user.profile_photo.representation(resize_to_limit: [200, 200]), class:"w-80 ml-4", id: "img-preview" %>
      <% end %>
    </div>
    <% user.errors.full_messages_for(:profile_photo).each do |message| %>
      <div class="invalid-feedback"><%= message %></div>
    <% end %>
  </div>

  <div class="col-10 mb-4" data-controller="upload">
    <%= form.label :images, class: "form-label" %>
    <%= form.file_field :images, multiple: true, direct_upload: true, data: { upload_target: 'input', action: "change->upload#uploadFiles" } %>
    <div id='imgs-preview'>
      <%= render 'products/image_slider', images: user.images%>
    </div>
    <% user.errors.full_messages_for(:images).each do |message| %>
      <div class="invalid-feedback"><%= message %></div>
    <% end %>
  </div>

  <div class="col-10">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/_user_info.html.erb
<div class="user-info card mb-3">
  <h5 class="card-header">User Info</h5>
  <div class="row g-0">
    <div class="col-md-4">
      <% if user.profile_photo.representable? %>
        <%= image_tag user.profile_photo.representation(resize_to_limit: [200, 200]), class:"w-80 ml-4" %>
      <% end %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%=user.name%></h5>
        <p class="card-text"><small class="text-muted">Phone Number: </small><%=user.phone_number%></p>
        <p class="card-text"><small class="text-muted">Address: </small><%=user.address%></p>
        <p class="card-text"><small class="text-muted">Gender: </small><%=user.gender%></p>
        <p class="card-text"><%=user.date_of_birth ? "<small class='text-muted'>Date of birth: #{user.date_of_birth.to_formatted_s(:long)} </small>".html_safe : ''%></p>
        <p class="card-text"><small class="text-muted">last updated <%=user.updated_at.to_formatted_s(:long)%></small></p>
        <%= link_to "Go User Detail", user_path(user.id), class: 'btn btn-primary' %><br />
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div id="edit-user">
  <h1>Edit User</h1>

  <%= render "form", user: @user %>
</div>

app/views/users/index.html.erb
<div id="users">
  <div class="row justify-content-between mb-4 align-items-center">
    <div class="col-8">
      <h1>User Management</h1>
    </div>
    <div class="col-4 text-end">
      <%= link_to "ADD User", new_user_path(), class: 'btn btn-primary' %>
    </div>
  </div>
  <div class="table-responsive">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Profile Photo</th>
          <th scope="col">Phone Number</th>
          <th scope="col">Gender</th>
          <th scope="col">DOB</th>
          <th scope="col">Address</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user|%>
          <tr>
            <th scope="row"><%= user.id%></th>
            <td><%= user.name%></td>
            <td>
              <% if user.profile_photo.representable? %>
                <%= image_tag user.profile_photo.representation(resize_to_limit: [200, 200]), class:"w-80 ml-4" %>
              <% end %>
            </td>
            <td><%= user.phone_number%></td>
            <td><%= user.gender%></td>
            <td><%= user.date_of_birth ? user.date_of_birth.to_formatted_s(:long) : ''%></td>
            <td><%= user.address%></td>
            <td class="text-center">
              <%= link_to "Detail", user_path(user.id), class: 'btn btn-info btn-sm m-2' %>
              <%= link_to "Edit", edit_user_path(user.id), class: 'btn btn-primary btn-sm m-2' %>
              <%= link_to "Delete", user_path(user),
                data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure you want to delete this?"
                }, class: 'btn btn-danger btn-sm m-2'%>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
  <%= paginate @users %>
</div>

app/views/users/new.html.erb
<div id="new-user">
  <h1>New User</h1>

  <%= render "form", user: @user %>
</div>

app/views/users/show.html.erb
<div id="user">
  <h1 class="mb-4">User Detail</h1>
  <%= render 'user_info', user: @user%>
</div>