config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: :registration
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'home/index'
  root to: 'home#index'

  resources :users
  resources :user_loans
  resources :products
  resources :product_variants
  resources :payment_schedules
  resources :invoices
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  description :string
#  images      :attachments
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Product < ApplicationRecord
  has_many :variants, class_name: 'ProductVariant', dependent: :destroy
  has_many_attached :images, dependent: :destroy
  accepts_nested_attributes_for :variants, allow_destroy: true

  validates :name, presence: true
  validates :description, length: { minimum: 200 }
  validates :images, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @products = Product.order(:id).page params[:page]
  end

  # rubocop:disable Metrics/MethodLength
  def show; end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  # rubocop:disable Metrics/MethodLength
  def edit; end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy

    redirect_to products_path, status: :ok
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, images: [],
                                                         variants_attributes: %i[id color dimension price qty weight _destroy])
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<p data-controller="product"></p>
<%= form_with model: product, class: 'row' do |form| %>
  <div class="col-10 mb-4">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
    <% product.errors.full_messages_for(:name).each do |message| %>
      <div class="invalid-feedback"><%= message %></div>
    <% end %>
  </div>

  <div class="col-10 mb-4">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
    <% product.errors.full_messages_for(:description).each do |message| %>
      <div class="invalid-feedback"><%= message %></div>
    <% end %>
  </div>

  <div class="col-10 mb-4">
    <%= form.label :images, class: "form-label" %>
    <%= form.file_field :images, multiple: true, direct_upload: true %>
    <div>
      <%= render 'image_slider', images: product.images%>
    </div>
    <% product.errors.full_messages_for(:images).each do |message| %>
      <div class="invalid-feedback"><%= message %></div>
    <% end %>
  </div>

  <%# Variants %>
  <div class="col-10 mb-4">
    <fieldset>
      <%= form.fields_for :variants, local: true do |f| %>
        <%= render 'variant_fields', f: f%>
      <% end %>

      <%= link_to_add_fields "Add Variant", form, :variants %>
      <p data-controller="variant"></p>
    </fieldset>
  </div>

  <div class="col-10">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/_image_slider.html.erb
<% images.each do |file| %>
  <% if file.representable? %>
    <%= image_tag file.representation(resize_to_limit: [200, 200]), class:"w-80 ml-4" %>
  <% end %>
<% end %>

app/views/products/_product_info.html.erb
<div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-4">
      <%= render 'image_slider', images: product.images%>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= product.name%></h5>
        <p class="card-text"><%= product.description%></p>
        <p class="card-text"><small class="text-muted">Last updated <%=product.updated_at.to_formatted_s(:long)%></small></p>
      </div>
    </div>
  </div>
</div>
<div class="card">
  <%= render 'product_variant_info', product_variants: product.variants%>
</div>

app/views/products/_product_variant_info.html.erb
<ol class="list-group list-group-numbered list-group-flush">
  <%product_variants.each do |variant|%>
    <li class="list-group-item d-flex justify-content-between align-items-start">
      <div class="ms-2 me-auto">
        <% if variant.color?%>
          Color: <strong><%=variant.color%></strong>
          <br />
        <%end%>
        <% if variant.price?%>
          Price: <strong><%=variant.price%>$</strong>
          <br />
        <%end%>
        <% if variant.dimension?%>
          Dimension: <strong><%=variant.dimension%></strong>
          <br />
        <%end%>
        <% if variant.weight?%>
          Weight: <strong><%=variant.weight%></strong>
          <br />
        <%end%>
      </div>
      <span class="badge bg-primary rounded-pill"><%=variant.qty%></span>
    </li>
  <%end%>
</ol>

app/views/products/_variant_fields.html.erb
<div class='nested-fields row border ms-1 mb-3 p-3'>
  <div class="col-6 mb-4">
    <%= f.label :color, class: "form-label" %>
    <%= f.text_field :color, class: "form-control" %>
  </div>

  <div class="col-6 mb-4">
    <%= f.label :dimension, class: "form-label" %>
    <%= f.text_field :dimension, class: "form-control" %>
  </div>

  <div class="col-6 mb-4">
    <%= f.label :price, class: "form-label" %>
    <%= f.text_field :price, type: :number, step: "any", class: "form-control" %>
  </div>

  <div class="col-6 mb-4">
    <%= f.label :qty, class: "form-label" %>
    <%= f.text_field :qty, type: :number, class: "form-control" %>
  </div>

  <div class="col-6 mb-4">
    <%= f.label :weight, class: "form-label" %>
    <%= f.text_field :weight, type: :number, step: "any", class: "form-control" %>
  </div>

  <div class="form-check">
    <%= f.check_box :_destroy, class: "form-check-input" %>
    <label class="form-check-label text-danger" for="flexCheckChecked">
      Delete
    </label>
  </div>
</div>

app/views/products/edit.html.erb
<div id="edit-product">
  <h1>Edit Product</h1>

  <%= render "form", product: @product %>
</div>

app/views/products/index.html.erb
<div id="products">
  <div class="row justify-content-between mb-4 align-items-center">
    <div class="col-8">
      <h1>Product Management</h1>
    </div>
    <div class="col-4 text-end">
      <%= link_to "ADD Product", new_product_path(), class: 'btn btn-primary' %>
    </div>
  </div>
  <div class="table-responsive">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Description</th>
          <th scope="col">Image</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product|%>
          <tr>
            <th scope="row"><%= product.id%></th>
            <td><%= product.name%></td>
            <td><%= product.description%></td>
            <td>
              <% product.images.take(1).each do |file| %>
                <% if file.representable? %>
                  <%= image_tag file.representation(resize_to_limit: [100, 100])%>
                <%end%>
              <%end%>
            </td>
            <td class="text-center">
              <%= link_to "Detail", product_path(product.id), class: 'btn btn-info btn-sm m-2' %>
              <%= link_to "Edit", edit_product_path(product.id), class: 'btn btn-primary btn-sm m-2' %>
              <%= link_to "Delete", product_path(product),
                data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure you want to delete this?"
                }, class: 'btn btn-danger btn-sm m-2'%>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
  <%= paginate @products %>
</div>

app/views/products/new.html.erb
<div id="new-product">
  <h1>New Product</h1>

  <%= render "form", product: @product %>
</div>

app/views/products/show.html.erb
<div id="product">
  <h1 class="mb-4">Product Detail</h1>
  <%= render 'product_info', product: @product%>
</div>