config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: :registration
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'home/index'
  root to: 'home#index'

  resources :users
  resources :user_loans
  resources :products
  resources :product_variants
  resources :payment_schedules
  resources :invoices
end

app/views/layouts/_nav.html.erb
<aside class='bd-sidebar'>
  <% if admin_signed_in? %>
    <nav class='collapse bd-links' id='system-nav'>

      <ul class='list-unstyled mb-0 py-3 pt-md-1'>
        <li class='mb-1'>
          <%= link_to "Log Out", destroy_admin_session_path, data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure you want to log out?"
                  }, class: 'btn d-inline-flex align-items-center rounded collapsed text-danger'%><br />
        </li>
        <li class='mb-1'>
          <%= link_to "User Management", users_path, class: 'btn d-inline-flex align-items-center rounded collapsed' %><br />
        </li>

        <li class='mb-1'>
          <%= link_to "Product Management", products_path, class: 'btn d-inline-flex align-items-center rounded collapsed' %><br />
        </li>

        <li class='mb-1'>
          <%= link_to "Loan Management", user_loans_path, class: 'btn d-inline-flex align-items-center rounded collapsed' %><br />
        </li>

        <li class='mb-1'>
          <%= link_to "Invoice Management", invoices_path, class: 'btn d-inline-flex align-items-center rounded collapsed' %><br />
        </li>
      </ul>
    </nav>
  <%end%>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoanSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container-xxl my-md-4 bd-layout">
      <%= render 'layouts/nav'%>
      <div class="overflow-scroll">
        <%= yield %>
      </div>
    </div>
  </body>
</html>